apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress
  labels:
    app: cpu-stress
  annotations:
    # Annotation for Litmus
    litmuschaos.io/chaos: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
      annotations:
        # Annotation for Litmus
        litmuschaos.io/chaos: "true"
    spec:
      containers:
        - name: cpu-stress
          image: iskorotkov/chaos-cpu-stress:v0.1.0
          env:
            - name: DIM
              value: "32"
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
